JOB_MAPPING = { 
    "Science": ["Data Analyst", "Engineering", "Education", "Information Technology", "Research", "Science", "Training"],
    "Service": ["Consulting", "Customer Service", "General Business", "Health Care Provider", "Human Resources", "Public Relations", "Sales", "Administrative"],
    "Creative": ["Advertising", "Art/Creative", "Design", "Marketing", "Project Management", "Writing/Editing"],
    "Strategic": ["Business Analyst", "Business Development", "Distribution", "Management", "Strategy/Planning", "Supply Chain"],
    "Legal": ["Legal"],
    "Finance": ["Accounting/Auditing", "Finance", "Financial Analyst"],
    "Manufacturing": ["Manufacturing", "Production", "Purchasing", "Quality Assurance"],
    "Other": ["Other"]
}

JOB_TYPE_MAPPING = {'Accounting/Auditing': 1, 
                    'Administrative': 2, 
                    'Advertising': 3, 
                    'Art/Creative': 4, 
                    'Business Analyst': 5, 
                    'Business Development': 6, 
                    'Consulting': 7, 
                    'Customer Service': 8, 
                    'Data Analyst': 9, 
                    'Design': 10, 
                    'Distribution': 11, 
                    'Education': 12, 
                    'Engineering': 13, 
                    'Finance': 14, 
                    'Financial Analyst': 15, 
                    'General Business': 16, 
                    'Health Care Provider': 17, 
                    'Human Resources': 18, 
                    'Information Technology': 19, 
                    'Legal': 20, 
                    'Management': 21, 
                    'Manufacturing': 22, 
                    'Marketing': 23, 
                    'Other': 24, 
                    'Product Management': 25, 
                    'Production': 26, 
                    'Project Management': 27, 
                    'Public Relations': 28, 
                    'Purchasing': 29, 
                    'Quality Assurance': 30, 
                    'Research': 31, 
                    'Sales': 32, 
                    'Science': 33, 
                    'Strategy/Planning': 34, 
                    'Supply Chain': 35, 
                    'Training': 36, 
                    'Writing/Editing': 37}

SENIORITY = ["junior", "medior", "intermediate", "senior", "internship"]
SCIENCE_HARD_SKILL = ["java", "javascript", "engineer", "engineering", "api", "ruby", "python", "database", "c++", "c#", "go", "rust", "cloud", "computer", "aws", "mongodb", "postgresql", "mysql", "sql", "kubernetes", "docker"]
DEVELOPER_CLASSIFICATION = ["backend", "back-end", "frontend", "front-end", "full-stack", "fullstack"]